apiVersion: v1
kind: Pod
metadata:
  name: test-loadastic
spec:
  containers:
    - name: test-loadastic
      image: github.com/slinkydeveloper/loadastic/test_image/kafka
      env:
        - name: BOOTSTRAP_URL
          value: my-cluster-kafka-bootstrap.kafka.svc:9092
        - name: TOPIC
          value: my-topic
